### ISSUE TITLE
您好 请问播放器是更新了吗？软件包名变成--WavPlayer

### ISSUE THREAD

**Issue by mountxing** [Guozhanxin/RTT-BeepPlayer-pkg#1]

**Comment by mountxing** [comment]
您好 请问播放器是更新了吗？软件包名变成--WavPlayer

**Comment by Guozhanxin** [comment]
不是，wavplayer 是另外一个大神做的，比这个优化的好，这个更多还是一个学习性质的

**Comment by balanceTWK** [comment]
> 不是，wavplayer 是另外一个大神做的，比这个优化的好，这个更多还是一个学习性质的

您谦虚了。
